/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_appsync_graphqlEndpoint": "https://4yn5ciwocndzdlfvdwdtw2j3vm.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-hql44wfsubforny3chfrpbf6om",
    "aws_cognito_identity_pool_id": "us-east-2:5b239463-c7fc-4f01-b511-ce4ccf3796ad",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_5d9Rish4P",
    "aws_user_pools_web_client_id": "5canv57l6pvj2hpbm3pf34aan3",
    "oauth": {}
};


export default awsmobile;
